ini_open("stateSettings.ini")
ini_write_real("General", "timer", global.timer)
ini_write_real("General", "lastTimer", global.lastTimer)
ini_write_real("General", "otherLastTimer", global.otherLastTimer)
ini_write_real("General", "state", global.stateIndex)
ini_write_real("General", "lastState", global.lastState)
ini_write_real("General", "otherLastState", global.otherLastState)
ini_write_real("General", "seed", global.seed)
ini_write_real("General", "lastSeed", global.lastSeed)
ini_write_real("General", "otherLastSeed", global.otherLastSeed)
ini_close()
